### ISSUE TITLE
Notion had change public link domain, need to redirect

### ISSUE THREAD

**Issue by thexclu** [lobre/docker-notion-proxy#2]
Thanks for developing this solution, I have been searching for a while about Nginx solution. However, notion [changed the public link domain](https://www.notion.so/blog/personalize-public-pages) to notion.site. Current solution need to redirect to notion.site. 
Any matter can solve this?
![image](https://user-images.githubusercontent.com/26009982/130021832-70dac444-4601-4882-bb8f-3d51fd9393ee.png)

also i had face this error as well:
![image](https://user-images.githubusercontent.com/26009982/130021760-fc05bfeb-5ded-44e1-81e9-44713d7cef99.png)

**Comment by lobre** [comment]
Hi,

I guess effectively that my solution does not work anymore. As Notion is evolving quickly, maintaining such a proxy can be difficult. I currently don’t have any use-case to use it. If Notion implements security to prevent that, it may not be possible to do it anymore.

However, if it is just the backend URL that changed, I suppose you can try to tweak the `nginx.tmpl` with the new one and see how it reacts.

https://github.com/lobre/docker-notion-proxy/blob/master/nginx.tmpl

Hope that it helps,
Loric

**Comment by thexclu** [comment]
I had tried tweak the nginx.tmpl, seem like the solution does not work anymore. thanks.

**Comment by coder-xiaotian** [comment]
> tweak

I had the same problem. Did you solve it?
